<?php

namespace Practice\Mageplaza\Model;

use Magento\Framework\Model\AbstractModel;
use Magento\Framework\DataObject\IdentityInterface;
use Practice\Mageplaza\Api\Data\WarehouseInterface;

class Warehouse extends AbstractModel implements IdentityInterface, WarehouseInterface
{
    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
    }

    public function getIdentities()
    {
        return [self::CACHE_TAG . '_' . $this->getId()];
    }
}