<?php

/*** @var Practice\First\Block\First $this */
echo $this->showWelcome();
$postCollection = $this->getPostCollection();
?>

<table>
    <tr>
        <th class="post-id">Id</th>
        <th class="post-name">Name</th>
        <th>Content</th>
    </tr>
    <?php
    foreach ($postCollection as $post){
        echo '<tr>
                    <td>'.$post->getPostId().'</td>
                    <td>'.$post->getName().'</td>
                    <td>'.$post->getPostContent().'</td>
                  </tr>';
    }
    ?>
</table>